module;

#if defined(_WINDOWS)
# if defined(_M_AMD64) && !defined(_AMD64_)
#   define _AMD64_
# endif
# if defined(_M_IX86) && !defined(_X68_)
#  define _X86_
# endif
#endif

#include <windef.h>
#include <WinBase.h>
#include <winnt.h>
#include <fileapi.h>

export module winapi.File;

#if !defined __INTELLISENSE__
import winapi.WinDef;
import winapi.WinError;
import winapi.WTypes;
import winapi.WinNT;

using winapi::DWORD;
#endif

namespace
{
    constexpr auto
	local_FILE_BEGIN    = FILE_BEGIN,
	local_FILE_CURRENT  = FILE_CURRENT,
	local_FILE_END	    = FILE_END;

    constexpr auto
	local_FILE_SHARE_DELETE     = FILE_SHARE_DELETE,
	local_FILE_SHARE_WRITE	    = FILE_SHARE_WRITE,
	local_FILE_SHARE_READ	    = FILE_SHARE_READ;

    constexpr auto
	local_CREATE_ALWAYS	    = CREATE_ALWAYS,
	local_CREATE_NEW	    = CREATE_NEW,
	local_OPEN_ALWAYS	    = OPEN_ALWAYS,
	local_OPEN_EXISTING	    = OPEN_EXISTING,
	local_TRUNCATE_EXISTING	    = TRUNCATE_EXISTING;

    constexpr DWORD
	local_FILE_ATTRIBUTE_READONLY		   = FILE_ATTRIBUTE_READONLY,
	local_FILE_ATTRIBUTE_HIDDEN		   = FILE_ATTRIBUTE_HIDDEN,
	local_FILE_ATTRIBUTE_SYSTEM		   = FILE_ATTRIBUTE_SYSTEM,
	local_FILE_ATTRIBUTE_DIRECTORY		   = FILE_ATTRIBUTE_DIRECTORY,
	local_FILE_ATTRIBUTE_ARCHIVE		   = FILE_ATTRIBUTE_ARCHIVE,
	local_FILE_ATTRIBUTE_DEVICE		   = FILE_ATTRIBUTE_DEVICE,
	local_FILE_ATTRIBUTE_NORMAL		   = FILE_ATTRIBUTE_NORMAL,
	local_FILE_ATTRIBUTE_TEMPORARY		   = FILE_ATTRIBUTE_TEMPORARY,
	local_FILE_ATTRIBUTE_SPARSE_FILE	   = FILE_ATTRIBUTE_SPARSE_FILE,
	local_FILE_ATTRIBUTE_REPARSE_POINT	   = FILE_ATTRIBUTE_REPARSE_POINT,
	local_FILE_ATTRIBUTE_COMPRESSED		   = FILE_ATTRIBUTE_COMPRESSED,
	local_FILE_ATTRIBUTE_OFFLINE		   = FILE_ATTRIBUTE_OFFLINE,
	local_FILE_ATTRIBUTE_NOT_CONTENT_INDEXED   = FILE_ATTRIBUTE_NOT_CONTENT_INDEXED,
	local_FILE_ATTRIBUTE_ENCRYPTED		   = FILE_ATTRIBUTE_ENCRYPTED,
	local_FILE_ATTRIBUTE_INTEGRITY_STREAM	   = FILE_ATTRIBUTE_INTEGRITY_STREAM,
	local_FILE_ATTRIBUTE_VIRTUAL		   = FILE_ATTRIBUTE_VIRTUAL,
	local_FILE_ATTRIBUTE_NO_SCRUB_DATA	   = FILE_ATTRIBUTE_NO_SCRUB_DATA,
	local_FILE_ATTRIBUTE_EA			   = FILE_ATTRIBUTE_EA,
	local_FILE_ATTRIBUTE_PINNED		   = FILE_ATTRIBUTE_PINNED,
	local_FILE_ATTRIBUTE_UNPINNED		   = FILE_ATTRIBUTE_UNPINNED,
	local_FILE_ATTRIBUTE_RECALL_ON_OPEN	   = FILE_ATTRIBUTE_RECALL_ON_OPEN,
	local_FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS = FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS;

    constexpr DWORD
	local_FILE_FLAG_BACKUP_SEMANTICS	   = FILE_FLAG_BACKUP_SEMANTICS,
	local_FILE_FLAG_DELETE_ON_CLOSE		   = FILE_FLAG_DELETE_ON_CLOSE,
	local_FILE_FLAG_NO_BUFFERING		   = FILE_FLAG_NO_BUFFERING,
	local_FILE_FLAG_OPEN_NO_RECALL		   = FILE_FLAG_OPEN_NO_RECALL,
	local_FILE_FLAG_OPEN_REPARSE_POINT	   = FILE_FLAG_OPEN_REPARSE_POINT,
	local_FILE_FLAG_OVERLAPPED		   = FILE_FLAG_OVERLAPPED,
	local_FILE_FLAG_POSIX_SEMANTICS		   = FILE_FLAG_POSIX_SEMANTICS,
	local_FILE_FLAG_RANDOM_ACCESS		   = FILE_FLAG_RANDOM_ACCESS,
	local_FILE_FLAG_SESSION_AWARE		   = FILE_FLAG_SESSION_AWARE,
	local_FILE_FLAG_SEQUENTIAL_SCAN		   = FILE_FLAG_SEQUENTIAL_SCAN,
	local_FILE_FLAG_WRITE_THROUGH		   = FILE_FLAG_WRITE_THROUGH;

    constexpr DWORD
	local_SECURITY_ANONYMOUS		   = SECURITY_ANONYMOUS,
	local_SECURITY_CONTEXT_TRACKING		   = SECURITY_CONTEXT_TRACKING,
	local_SECURITY_DELEGATION		   = SECURITY_DELEGATION,
	local_SECURITY_EFFECTIVE_ONLY		   = SECURITY_EFFECTIVE_ONLY,
	local_SECURITY_IDENTIFICATION		   = SECURITY_IDENTIFICATION,
	local_SECURITY_IMPERSONATION		   = SECURITY_IMPERSONATION;
}

#undef FILE_BEGIN
#undef FILE_CURRENT
#undef FILE_END
#undef FILE_SHARE_DELEETE
#undef FILE_SHARE_WRITE
#undef FILE_SHARE_READ

#undef CREATE_ALWAYS
#undef CREATE_NEW
#undef OPEN_ALWAYS
#undef OPEN_EXISTING
#undef TRUNCATE_EXISTING

#undef FILE_ATTRIBUTE_READONLY
#undef FILE_ATTRIBUTE_HIDDEN
#undef FILE_ATTRIBUTE_SYSTEM
#undef FILE_ATTRIBUTE_DIRECTORY
#undef FILE_ATTRIBUTE_ARCHIVE
#undef FILE_ATTRIBUTE_DEVICE
#undef FILE_ATTRIBUTE_NORMAL
#undef FILE_ATTRIBUTE_TEMPORARY
#undef FILE_ATTRIBUTE_SPARSE_FILE
#undef FILE_ATTRIBUTE_REPARSE_POINT
#undef FILE_ATTRIBUTE_COMPRESSED
#undef FILE_ATTRIBUTE_OFFLINE
#undef FILE_ATTRIBUTE_NOT_CONTENT_INDEXED
#undef FILE_ATTRIBUTE_ENCRYPTED
#undef FILE_ATTRIBUTE_INTEGRITY_STREAM
#undef FILE_ATTRIBUTE_VIRTUAL
#undef FILE_ATTRIBUTE_NO_SCRUB_DATA
#undef FILE_ATTRIBUTE_EA
#undef FILE_ATTRIBUTE_PINNED
#undef FILE_ATTRIBUTE_UNPINNED
#undef FILE_ATTRIBUTE_RECALL_ON_OPEN
#undef FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS

#undef FILE_FLAG_BACKUP_SEMANTICS
#undef FILE_FLAG_DELETE_ON_CLOSE
#undef FILE_FLAG_NO_BUFFERING
#undef FILE_FLAG_OPEN_NO_RECALL
#undef FILE_FLAG_OPEN_REPARSE_POINT
#undef FILE_FLAG_OVERLAPPED
#undef FILE_FLAG_POSIX_SEMANTICS
#undef FILE_FLAG_RANDOM_ACCESS
#undef FILE_FLAG_SESSION_AWARE
#undef FILE_FLAG_SEQUENTIAL_SCAN
#undef FILE_FLAG_WRITE_THROUGH

#undef SECURITY_ANONYMOUS
#undef SECURITY_CONTEXT_TRACKING
#undef SECURITY_DELEGATION
#undef SECURITY_EFFECTIVE_ONLY
#undef SECURITY_IDENTIFICATION
#undef SECURITY_IMPERSONATION

#undef CreateFile

namespace winapi
{
    export constexpr auto
	FILE_BEGIN	= local_FILE_BEGIN,
	FILE_CURRENT	= local_FILE_CURRENT,
	FILE_END	= local_FILE_END;

    export constexpr auto
	FILE_SHARE_DELEETE  = local_FILE_SHARE_DELETE,
	FILE_SHARE_WRITE    = local_FILE_SHARE_WRITE,
	FILE_SHARE_READ	    = local_FILE_SHARE_READ;

    export constexpr auto
	CREATE_ALWAYS	    = local_CREATE_ALWAYS,
	CREATE_NEW	    = local_CREATE_NEW,
	OPEN_ALWAYS	    = local_OPEN_ALWAYS,
	OPEN_EXISTING	    = local_OPEN_EXISTING,
	TRUNCATE_EXISTING   = local_TRUNCATE_EXISTING;

    export constexpr auto
	FILE_ATTRIBUTE_READONLY			= local_FILE_ATTRIBUTE_READONLY,
	FILE_ATTRIBUTE_HIDDEN			= local_FILE_ATTRIBUTE_HIDDEN,
	FILE_ATTRIBUTE_SYSTEM			= local_FILE_ATTRIBUTE_SYSTEM,
	FILE_ATTRIBUTE_DIRECTORY		= local_FILE_ATTRIBUTE_DIRECTORY,
	FILE_ATTRIBUTE_ARCHIVE			= local_FILE_ATTRIBUTE_ARCHIVE,
	FILE_ATTRIBUTE_DEVICE			= local_FILE_ATTRIBUTE_DEVICE,
	FILE_ATTRIBUTE_NORMAL			= local_FILE_ATTRIBUTE_NORMAL,
	FILE_ATTRIBUTE_TEMPORARY		= local_FILE_ATTRIBUTE_TEMPORARY,
	FILE_ATTRIBUTE_SPARSE_FILE		= local_FILE_ATTRIBUTE_SPARSE_FILE,
	FILE_ATTRIBUTE_REPARSE_POINT		= local_FILE_ATTRIBUTE_REPARSE_POINT,
	FILE_ATTRIBUTE_COMPRESSED		= local_FILE_ATTRIBUTE_COMPRESSED,
	FILE_ATTRIBUTE_OFFLINE			= local_FILE_ATTRIBUTE_OFFLINE,
	FILE_ATTRIBUTE_NOT_CONTENT_INDEXED	= local_FILE_ATTRIBUTE_NOT_CONTENT_INDEXED,
	FILE_ATTRIBUTE_ENCRYPTED		= local_FILE_ATTRIBUTE_ENCRYPTED,
	FILE_ATTRIBUTE_INTEGRITY_STREAM		= local_FILE_ATTRIBUTE_INTEGRITY_STREAM,
	FILE_ATTRIBUTE_VIRTUAL			= local_FILE_ATTRIBUTE_VIRTUAL,
	FILE_ATTRIBUTE_NO_SCRUB_DATA		= local_FILE_ATTRIBUTE_NO_SCRUB_DATA,
	FILE_ATTRIBUTE_EA			= local_FILE_ATTRIBUTE_EA,
	FILE_ATTRIBUTE_PINNED			= local_FILE_ATTRIBUTE_PINNED,
	FILE_ATTRIBUTE_UNPINNED			= local_FILE_ATTRIBUTE_UNPINNED,
	FILE_ATTRIBUTE_RECALL_ON_OPEN		= local_FILE_ATTRIBUTE_RECALL_ON_OPEN,
	FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS	= local_FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS;

    export constexpr auto
	FILE_FLAG_BACKUP_SEMANTICS	   = local_FILE_FLAG_BACKUP_SEMANTICS,
	FILE_FLAG_DELETE_ON_CLOSE	   = local_FILE_FLAG_DELETE_ON_CLOSE,
	FILE_FLAG_NO_BUFFERING		   = local_FILE_FLAG_NO_BUFFERING,
	FILE_FLAG_OPEN_NO_RECALL	   = local_FILE_FLAG_OPEN_NO_RECALL,
	FILE_FLAG_OPEN_REPARSE_POINT	   = local_FILE_FLAG_OPEN_REPARSE_POINT,
	FILE_FLAG_OVERLAPPED		   = local_FILE_FLAG_OVERLAPPED,
	FILE_FLAG_POSIX_SEMANTICS	   = local_FILE_FLAG_POSIX_SEMANTICS,
	FILE_FLAG_RANDOM_ACCESS		   = local_FILE_FLAG_RANDOM_ACCESS,
	FILE_FLAG_SESSION_AWARE		   = local_FILE_FLAG_SESSION_AWARE,
	FILE_FLAG_SEQUENTIAL_SCAN	   = local_FILE_FLAG_SEQUENTIAL_SCAN,
	FILE_FLAG_WRITE_THROUGH		   = local_FILE_FLAG_WRITE_THROUGH;

    export constexpr DWORD
	SECURITY_ANONYMOUS		   = local_SECURITY_ANONYMOUS,
	SECURITY_CONTEXT_TRACKING	   = local_SECURITY_CONTEXT_TRACKING,
	SECURITY_DELEGATION		   = local_SECURITY_DELEGATION,
	SECURITY_EFFECTIVE_ONLY		   = local_SECURITY_EFFECTIVE_ONLY,
	SECURITY_IDENTIFICATION		   = local_SECURITY_IDENTIFICATION,
	SECURITY_IMPERSONATION		   = local_SECURITY_IMPERSONATION;

    export using ::SetFilePointerEx;
    export using ::ReadFile;
    export using ::WriteFile;
    export using ::CreateFileW;
    export using ::CreateFileA;

#if defined _UNICODE || defined UNICODE
    export auto &CreateFile = CreateFileW;
#else
    export auto &CreateFile = CreateFileA;
#endif
}
