module;

#include <wx/artprov.h>

export module wx.Core:Miscellaneous;

namespace wx
{
    export using ArtProvider = wxArtProvider;

    export constexpr auto const
	ART_ERROR		= wxART_ERROR,
	ART_QUESTION		= wxART_QUESTION,
	ART_WARNING		= wxART_WARNING,
	ART_INFORMATION		= wxART_INFORMATION,
	ART_ADD_BOOKMARK	= wxART_ADD_BOOKMARK,
	ART_DEL_BOOKMARK	= wxART_DEL_BOOKMARK,
	ART_HELP_SIDE_PANEL	= wxART_HELP_SIDE_PANEL,
	ART_HELP_SETTINGS	= wxART_HELP_SETTINGS,
	ART_HELP_BOOK		= wxART_HELP_BOOK,
	ART_HELP_FOLDER		= wxART_HELP_FOLDER,
	ART_HELP_PAGE		= wxART_HELP_PAGE,
	ART_GO_BACK		= wxART_GO_BACK,
	ART_GO_FORWARD		= wxART_GO_FORWARD,
	ART_GO_UP		= wxART_GO_UP,
	ART_GO_DOWN		= wxART_GO_DOWN,
	ART_GO_TO_PARENT	= wxART_GO_TO_PARENT,
	ART_GO_HOME		= wxART_GO_HOME,
	ART_GOTO_FIRST		= wxART_GOTO_FIRST;

    export constexpr auto const
	ART_GOTO_LAST		= wxART_GOTO_LAST,
	ART_PRINT		= wxART_PRINT,
	ART_HELP		= wxART_HELP,
	ART_TIP			= wxART_TIP,
	ART_REPORT_VIEW		= wxART_REPORT_VIEW,
	ART_LIST_VIEW		= wxART_LIST_VIEW,
	ART_NEW_DIR		= wxART_NEW_DIR,
	ART_FOLDER		= wxART_FOLDER,
	ART_FOLDER_OPEN		= wxART_FOLDER_OPEN,
	ART_GO_DIR_UP		= wxART_GO_DIR_UP,
	ART_EXECUTABLE_FILE	= wxART_EXECUTABLE_FILE,
	ART_NORMAL_FILE		= wxART_NORMAL_FILE,
	ART_TICK_MARK		= wxART_TICK_MARK,
	ART_CROSS_MARK		= wxART_CROSS_MARK,
	ART_MISSING_IMAGE	= wxART_MISSING_IMAGE,
	ART_NEW			= wxART_NEW,
	ART_FILE_OPEN		= wxART_FILE_OPEN,
	ART_FILE_SAVE		= wxART_FILE_SAVE;

    export constexpr auto const
	ART_FILE_SAVE_AS	= wxART_FILE_SAVE_AS,
	ART_DELETE		= wxART_DELETE,
	ART_COPY		= wxART_COPY,
	ART_CUT			= wxART_CUT,
	ART_PASTE		= wxART_PASTE,
	ART_UNDO		= wxART_UNDO,
	ART_REDO		= wxART_REDO,
	ART_PLUS		= wxART_PLUS,
	ART_MINUS		= wxART_MINUS,
	ART_CLOSE		= wxART_CLOSE,
	ART_QUIT		= wxART_QUIT,
	ART_FIND		= wxART_FIND,
	ART_FIND_AND_REPLACE	= wxART_FIND_AND_REPLACE,
	ART_FULL_SCREEN		= wxART_FULL_SCREEN,
	ART_EDIT		= wxART_EDIT,
	ART_HARDDISK		= wxART_HARDDISK,
	ART_FLOPPY		= wxART_FLOPPY,
	ART_CDROM		= wxART_CDROM,
	ART_REMOVABLE		= wxART_REMOVABLE,
	ART_WX_LOGO		= wxART_WX_LOGO;

    export constexpr auto const
	ART_TOOLBAR		= wxART_TOOLBAR,
	ART_MENU		= wxART_MENU,
	ART_BUTTON		= wxART_BUTTON,
	ART_FRAME_ICON		= wxART_FRAME_ICON,
	ART_CMN_DIALOG		= wxART_CMN_DIALOG,
	ART_HELP_BROWSER	= wxART_HELP_BROWSER,
	ART_MESSAGE_BOX		= wxART_MESSAGE_BOX,
	ART_OTHER		= wxART_OTHER;
}
