include_guard(DIRECTORY)

set(LOCAL_MODULE_DIR_PATH "${CMAKE_CURRENT_LIST_DIR}")

list(REMOVE_ITEM CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
list(PREPEND	 CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}")
